language: scala
scala:
  - "2.10.4"
jdk:
  - oraclejdk7
script: sbt ++$TRAVIS_SCALA_VERSION assembly test
notifications:
  email:
    recipients:
      - me@baigang.net
before_install:
  - sudo apt-get install libsnappy1 libsnappy-dev

